#!/bin/bash
set -e

if ! command -v buf &> /dev/null
then
  bash ../scripts/setup.sh
fi

buf lint --error-format=json || (echo "Please run 'buf lint' and fix the errors" && exit 1)
buf format -w
git update-index --assume-unchanged gen/ --again
