name: Build and bump tag

on:
  push:
    branches:
      - main
      - feature/*
      - feat/*
      - hotfix/*
      - release/*
  pull_request: 
    types: 
      - closed

permissions: 
  contents: write
  packages: write
  pull-requests: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          push: false
          lint: true
          format: true
          token: ${{ secrets.BUF_TOKEN }}
          setup_only: false
      - name: Generate Protobuf Artifacts
        run: bash ./scripts/build.sh
      - name: Commit Builds
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git rm --cached gen -r || true
          git update-index --no-assume-unchanged gen/
          git add -f gen
          git commit --no-verify -m "chore: generate protobuf artifacts" || true
          git push || true
  tag:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name:  'Automated Version Bump'
        uses: phish108/autotag-action@v1.1.55
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          with-v: "true"