name: Build and bump tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@popberry-ai'
      - name: Install dependencies
        run: npm install
      - name: Generate Protobuf Artifacts
        run: npm run generate
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN }} #fix later
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '["proto/**/*","gen/go/**/*"]'
          github_token: ${{ secrets.TOKEN }} #fix later
      - name: Publish package
        run: npm publish