name: Build and bump tag

on:
  push:
    branches:
      - main

permissions: 
  contents: write
  packages: write
  pull-requests: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.TOKEN }} #fix later
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          push: false
          lint: true
          format: true
          token: ${{ secrets.BUF_TOKEN }}
          setup_only: false
      - name: Generate Protobuf Artifacts
        run: bash ./scripts/build.sh
      - name: Commit Builds
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git rm --cached gen -r || true
          git update-index --no-assume-unchanged gen/
          git add -f gen
          git commit --no-verify -m "chore: generate protobuf artifacts" || true
          git push || true
  tag:
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        with:
          tag-prefix:  'v'
          default-bump:  'patch'